### ISSUE TITLE
missing block/instructions to import pandas

### ISSUE THREAD

**Issue by rjlatail** [learn-co-curriculum/dsc-more-on-missing-data-lab#2]
## Link to Canvas

https://learning.flatironschool.com/courses/7244/assignments/272755?module_item_id=657901

## Issue Subtype

- [ ] Master branch code
- [ ] Solution branch code
- [ ] Code tests
- [ ] Layout/rendering issue
- [x ] Instructions unclear
- [ ] Other (explain below)

### Source

```
n/a
```

### Concern

I don't know if this is intentional, but in every other lab you typically start with a code block with instructions to import
any necessary modules, but you omitted that in this lab.  

## (Optional) Proposed Solution

I think you need to import pandas and matplotlib.pyplot

## What OS Are You Using?

- [ ] OS X
- [ x] Windows
- [ ] WSL
- [ ] Linux
- [ ] Saturn Cloud from Canvas

**Comment by bpurdy-ds** [comment]
Thanks for flagging this. That is typically how it is done, but apparently this lab was written a little different where the Python libraries are introduced as needed. While your suggestion is optimal, it is also good to see that you can bring in the libraries as needed as it is in this lab.
